spring:
    datasource:
      url: jdbc:mysql://localhost:3306/catalogsecure
      username: root
      password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          globally_quoted_identifiers: true
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
          show_sql: true
          use_sql_comments: true
    sql:
      init:
        mode: never
        continue-on-error: false